# Generated by Django 2.2.3 on 2019-09-22 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pinax_badges', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='badgeaward',
            table='brabeion_badgeaward',
        ),
    ]
